version: "3"
services:
  bitcoind:
    build: ./bitcoind
    volumes:
      - /s/bitcoind/blocks:/bitcoin/blocks/
      - /s/bitcoind/chainstate:/bitcoin/chainstate/
    ports:
      - "8333:8333"
    expose:
      - "8332"
      
  mongo:
    build: ./mongo
    container_name: mongo
    restart: always
    depends_on:
      - bitcoind
    expose:
      - 27017
      - 28017
    volumes:
      - "/var/lib/mongodb:/data/db"
      - "/var/backups/mongodb:/var/backups/mongodb"

  flask:
    build: ./flask
    container_name: flask
    restart: always
    depends_on:
      - mongo
    expose:
      - 5000
 
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:8080"

